// examples/nextjs/pages/index.tsx
export default function Web() {
  async function createFakeUser() {
    await fetch('/api/users', {
      method: 'POST',
      body: JSON.stringify({ id: 'foo' }),
    });
  }

  return (
    <div>
      <h1>Web</h1>
      <button onClick={() => createFakeUser()}>Trigger</button>
    </div>
  );
}

// examples/nuxtjs/pages/index.vue
<script setup lang="ts">
const { data } = await useFetch('/api/spera');

async function createFakeUser() {
  await $fetch('/api/users', {
    method: 'post',
    body: { id: 'foo' },
  });
}
</script>

<template>
  <div>
    <h1>Home page</h1>

    <button @click="createFakeUser">Create user</button>
    <!-- {{ data }} -->
  </div>
</template>
